# Generated by Django 4.1.6 on 2023-07-29 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500, verbose_name='Дополнительная опция')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
                'ordering': ['option'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='stars',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звёзд'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Транспорт если есть'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.ImageField(upload_to='media/trip', verbose_name='Рекламный баннер'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/trip', verbose_name='Изображение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalimages', to='product.trip')),
            ],
            options={
                'verbose_name': 'Еще фото',
                'verbose_name_plural': 'Еще фото',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='product.additionaloptions', verbose_name='Дополнительные опции'),
        ),
    ]
