# Generated by Django 4.2.3 on 2023-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_additionaloptions_trip_stars_alter_trip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала экскурсии'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.CharField(max_length=400, verbose_name='Продолжительность экскурсии'),
        ),
    ]
