# Generated by Django 4.2.3 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_trip_data_alter_trip_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
