# Generated by Django 4.1.6 on 2023-08-02 12:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_trip_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='decription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
