# Generated by Django 4.1.7 on 2023-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='wiki_autor',
            field=models.CharField(choices=[('Товарищ Генеральный директор', 'Генеральный директор'), ('батюшка бухгалтер', 'Бухгалтер'), ('исполнительный директоришка', 'Исполнительный директор'), ('Стажеришка', 'Стажер')], max_length=200, verbose_name='Автор инструкции'),
        ),
    ]
