# Generated by Django 4.1.7 on 2023-03-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_name', models.CharField(max_length=200, verbose_name='Тема инструкции')),
                ('wiki_date', models.DateField(default=datetime.date.today, verbose_name='Дата последнего редактирования')),
                ('wiki_autor', models.CharField(choices=[('GD', 'Генеральный директор'), ('BG', 'Бухгалтер'), ('ID', 'Исполнительный директор'), ('Jun', 'Стажер')], max_length=200, verbose_name='Автор инструкции')),
                ('wiki_url', models.URLField(verbose_name='Ссылка на документацию')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
    ]
