# Generated by Django 4.1.6 on 2023-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название компании')),
                ('manager', models.CharField(max_length=400, verbose_name='ФИО Менеджера')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('referal', models.BooleanField(default=False, verbose_name='Партнер в бонусной системе')),
                ('requisites', models.FileField(blank=True, null=True, upload_to='', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
