# Generated by Django 4.1.6 on 2023-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
