# Generated by Django 4.1.6 on 2023-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание менеджера'),
        ),
    ]
