# Generated by Django 4.1.6 on 2023-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_manager_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='prof',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
