# Generated by Django 4.1.6 on 2023-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Центральный офис')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='Вотсапп')),
                ('tg', models.CharField(max_length=200, verbose_name='Телеграмм')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='document/', verbose_name='Файл'),
        ),
    ]
