# Generated by Django 4.1.6 on 2023-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_contacts_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
