# Generated by Django 4.1.7 on 2023-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employees_prof',
            field=models.CharField(choices=[('Товарищ Генеральный директор', 'Генеральный директор'), ('батюшка бухгалтер', 'Бухгалтер'), ('исполнительный директоришка', 'Исполнительный директор'), ('Стажеришка', 'Стажер')], default='Стажеришка', max_length=30, verbose_name='Должность'),
        ),
    ]
