# Generated by Django 4.1.7 on 2023-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_quest', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('question_answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('question_topic', models.CharField(choices=[('Фин', 'Финансы'), ('Пр-жи', 'Продажи'), ('Марк-г', 'Маркетинг')], max_length=200, verbose_name='Тема')),
            ],
        ),
    ]
