# Generated by Django 4.1.7 on 2023-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('employees_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('employees_prof', models.CharField(choices=[('GD', 'Генеральный директор'), ('BG', 'Бухгалтер'), ('ID', 'Исполнительный директор'), ('Jun', 'Стажер')], default='Jun', max_length=30, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
