# Generated by Django 4.1.7 on 2023-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_main_main_ipg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='main_ipg',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Картинка'),
        ),
    ]
